# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: ['Homepage of Qian Chen']
description: ['E-mail: chenqian2020@sjtu.edu.cn',"Organization: Shanghai Jiao Tong University"]